### ISSUE TITLE
Null handling?

### ISSUE THREAD

**Issue by friday** [then/then-mongo#13]
Part of what appeals to me with promises is avoiding exception handling in multiple places. I can use Promise.all or a chain, and handle exceptions and errors via `catch` in one place and still separate between different type of exceptions. Bluebird makes this even easier: http://bluebirdjs.com/docs/api/catch.html

The mongodb API goes back in time before promises and don't "reject promises", but rather handle errors. Null results aren't errors, so for example `db.user.findOne({name: 'I dont exist'})` will return null and no error.

then-mongo works the same. If I run this with then-mongo it will log "foundOne null":
```js
db.user.findOne({_id: NaN})
  .then(user => console.log('FoundOne', user))
  .catch(err => console.log('caught', err));
```
While being as expected and consistent with the mongodb APIs, it means you have to handle null results with conditions:

```js
db.user.findOne({_id: NaN})
  .then(user => {
    if (user === null) {
      return Promise.reject(new Error('User is null'));
    }
    console.log('FoundOne', user);
  })
  .catch(err => console.log('caught', err));
```
This will log "caught Error: User is null" (and the stack trace), but it's not very neat.

Any suggestions or plans on a neater way to handle this?

**Comment by ForbesLindesay** [comment]
You don't need to wrap exceptions up like that, just throw them.  Once you do that, I think this works pretty well.

```js
db.user.findOne({_id: NaN})
  .then(user => {
    if (user === null) {
      throw new Error('User is null');
    }
    console.log('FoundOne', user);
  })
  .catch(err => console.log('caught', err));
```

Attempting to load a record you're not sure exists is a pretty common pattern.  It's much easier to just handle `null` as a possible response, than it is to pick out a special "does not exist" error from a set of error codes.  It's also relatively slow to create exceptions, so could lead to performance bottlenecks.

I'm going to stick to the current approach.  You can always write a simple `notnull` helper:

```js
function notnull(value) {
  if (value == null) {
    throw new Error('Did not expect null');
  }
  return value;
}

db.user.findOne({_id: NaN})
  .then(notnull)
  .then(user => console.log('FoundOne', user))
  .catch(err => console.log('caught', err));
```

**Comment by friday** [comment]
Thank you for the detailed reply! :)
